name: Docker build CI

on:
  push:
    branches:
      - main

jobs:
    build_docker_image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: "${{ secrets.DOCKERHUB_USERNAME }}/test"
