name: unit test

on:
  push:
    branches:
      - main

jobs:
    unit:
      env:
        JAVA_VERSION: '11'
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: run l
          run: pip install --no-cache-dir -r requirements.txt

        - name: run unit
          env:
            GH_TOKEN: ${{secrets.GH_TOKEN}}
            TEST: XYZ
          run:
           - python3 test_app.py
           - echo $TEST
           - echo $JAVA_VERSION
