name: run unit test

on:
  push:
    branch:
       - main

jobs:
  unittest:
    runs_on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: run l
          run: |
            - pip install --no-cache-dir -r requirements.txt

        - name: run unit
          run: python3 test_app.py
