name: unit test

on:
  push:
    branches:
      - mainn

jobs:
  unit:
    env:
      JAVA_VERSION: "11"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: run pip
        run: python -m pip install --upgrade pip
        shell: bash

      - name: install
        run: |
        echo "ruff==0.1.11\ncoverage" >> requirements.txt
        cat requirements.txt
        pip install -r requirements.txt

      - name: lint
        run: ruff --output-format=github .
        continue-on-error: true

      - name: run unit
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          TEST: XYZ
        run: |
          coverage run test_app.py
          coverage report -m
          coverage html

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: htmlcov/index.html

  job_series:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - name: "series"
        run: ls

  job_pl:
    runs-on: ubuntu-latest
    steps:
      - name: "|||"
        run: ls
