name: unit test

on:
  push:
    branches:
      - main

jobs:
    unit:
      runs_on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: run l
          run: pip install --no-cache-dir -r requirements.txt

        - name: run unit
          run: python3 test_app.py
