name: unit test

on:
  push:
    branches:
      - main

jobs:
    unit:
      env:
        JAVA_VERSION: '11'
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: run pip
          run: python -m pip install --upgrade pip
          shell: bash

        - name: intall
          run: pip install -r requirements.txt

        - name: lint
          run: ruff --output-format=github .
          continue-on-error: true




        - name: run unit
          env:
            GH_TOKEN: ${{secrets.GH_TOKEN}}
            TEST: XYZ
          run: |
           coverage run test_app.py
           coverage report -m
           coverage html
